config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :warehouses, only:[:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'add_category', on: :member
    post 'register_category', on: :member
    get 'search', on: :collection
    get 'confirm', on: :member
    patch 'activate', on: :member
    get 'disabled', on: :collection
  end
  resources :providers, only:[:index, :show, :new, :create] 
  resources :product_models, only:[:index, :show, :new, :create, :edit, :update] do
    patch 'enable', on: :member
    post 'product_entry', on: :member
  end
  resources :product_bundles, only:[:index, :new, :create, :show]
  resources :categories, only:[:index, :show, :new, :create]
  resources :product_items, only:[:new]
  get '/product_items/entry', to: 'product_items#entry'
  post '/product_items/entry', to: 'product_items#process_entry'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do #versionamento de api
      resources :warehouses, only:[:index, :show, :create]
      resources :product_models, only:[:index, :show, :create]
      resources :suppliers, only:[:index, :show, :create]
    end
    
  end
  

end

app/models/product_model.rb
require 'securerandom'

class ProductModel < ApplicationRecord
  enum status: {disabled: 0, enabled: 1}
  belongs_to :provider
  belongs_to :category
  has_many :product_items
  has_many :product_bundle_items
  has_many :product_bundles, through: :product_bundle_items

  before_validation do
    if self.sku == nil
      self.sku = generate_sku
    end
  end

  validates :name, :weight, :height, :length, :width, presence: true
  validates :weight, :height, :length, :width,  numericality: {greater_than: 0}
  validates :sku, length: { is: 20 }, uniqueness: true

  def dimensions
    "#{height} x #{width} x #{length}" 
  end

  private

  def generate_sku
    sku = SecureRandom.alphanumeric(20)    
    sku.upcase!
  end
 
end

app/controllers/api/v1/product_models_controller.rb
class Api::V1::ProductModelsController < Api::V1::ApiController
  def index
    product_models = ProductModel.all
    render json: product_models.as_json(except: [:created_at, :updated_at],
                                        methods: [:dimensions],
                                        include: {provider: {except: [:created_at, :updated_at]},
                                                  category: {only: [:name, :id]} }), status: 200
  end

  def show
      product_model = ProductModel.find(params[:id])
      render json: product_model.as_json(except: [:created_at, :updated_at],
                                         methods: [:dimensions],
                                         include: {provider: {except: [:created_at, :updated_at]},
                                                   category: {only: [:name, :id]} }), status: 200
  end

  def create
    pm_params = params.permit(:name, :weight, :height, :length, :width, :provider_id, :category_id)
    pm = ProductModel.new(pm_params)

    if pm.save
      render json: pm.as_json(except: [:created_at, :updated_at],
                                         methods: [:dimensions],
                                         include: {provider: {except: [:created_at, :updated_at]},
                                                   category: {only: [:name, :id]} }), status: 201
    
    else
      render json: pm.errors.full_messages, status: 422
    end
  end

end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def edit
    @product_model = ProductModel.find(params[:id])
    @errors = []
  end
  
  def update
    product_model_params = params.require(:product_model).permit(:name, :weight,
                                                                 :length, :height, :width,
                                                                 :provider_id, :category_id)

    @product_model = ProductModel.find(params[:id])
    @product_model.update(product_model_params)

    if @product_model.save
      redirect_to @product_model
    else
      @errors = @product_model.errors.full_messages
      flash.now[:alert] = 'Não foi possível editar o produto'
      render 'edit'
    end

  end

  def index
    @products = ProductModel.all
  end

  def show
    @product_model = ProductModel.find(params[:id])
    @items = @product_model.product_items.group(:warehouse).count
    @warehouses = Warehouse.all
 
    @error = nil
  end

  def new
    @product_model = ProductModel.new
    @errors = []
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :weight,
                                                                 :length, :height, :width,
                                                                 :provider_id, :category_id)
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto registrado com sucesso!'
    else
      flash.now[:alert] = 'Não foi possível gravar o produto'
      @errors = @product_model.errors.full_messages
      render 'new'
    end
  end

  def product_entry
    pe = ProductEntry.new(quantity: params[:quantity], warehouse_id: params[:warehouse_id],
      product_model_id: params[:id])

    if pe.process
      redirect_to product_model_path(params[:id]), notice: 'Produtos cadastrados com sucesso!'
    else
      @product_model = ProductModel.find(params[:id])
      @items = @product_model.product_items.group(:warehouse).count
      @warehouses = Warehouse.all

      if !pe.valid_quantity?
        @error = 'Quantidade inválida'
      elsif !pe.valid_category?
        @error = "Este galpão não permite itens da categoria #{ProductModel.find(pe.product_model_id).category.name}"
      end
      flash.now[:alert] = 'Não foi possível dar entrada nos itens'
      render 'show' 
    end
  end

  def enable
    pm = ProductModel.find(params[:id])

    if pm.enabled?
      pm.disabled!
    else
      pm.enabled!
    end

    redirect_to product_models_path
  end

end

app/views/product_models/edit.html.erb
<h3>Editar Produto</h3>

<div style="width: 46rem;">
  <% unless @errors == []%>
    <div class="alert alert-warning">
      <ul>
        <% @errors.each do |msg| %>
          <li><%=msg%></li>
        <%end%>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @product_model) do |f|%>
    <div class="form-group">
      <%= f.label :name, 'Nome'%>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :weight, 'Peso'%>
      <%= f.text_field :weight, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :height, 'Altura'%>
      <%= f.text_field :height, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :width, 'Largura'%>
      <%= f.text_field :width, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :length, 'Profundidade'%>
      <%= f.text_field :length, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :category_id, 'Categoria'%><br>
      <%= f.collection_select(:category_id, Category.all, :id, :name)%>
    </div>
    <br>    
    <div class="form-group">
      <%= f.label :provider_id, 'Fornecedor'%><br>
      <%= f.collection_select(:provider_id, Provider.all, :id, :trading_name) %>
    </div>
    <br>
    <%= f.submit 'Editar', class: 'btn btn-success'%>
  <%end%>
</div>

app/views/product_models/index.html.erb
<h3>Lista de modelos de produto</h3>

<%if @products.empty? %>
  <p>Nenhum produto cadastrado.</p>
<% else %>
  <p>Produtos cadastrados: <%= @products.count %></p>
  <br>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Produto</th>
      <th>Categoria</th>
    </tr>
  </thead>
    <% @products.each do |p| %>
      <tr id = <%=p.id%>>
        <% if p.enabled? %>
          <td style="color: green;"><%= p.enum_name(:status, p.status) %></td>
        <% else %>
          <td style="color: #dc3545;"><%= p.enum_name(:status, p.status) %></td>
        <% end %>
        <td><%= p.name %></td>
        <td><%= p.category.name %></td>
        <td><%= link_to 'Detalhes', p %></td>
        <% if user_signed_in?%>
          <td><%= link_to 'Editar', edit_product_model_path(p.id)%></td>
          <% if p.enabled? %>
            <td><%= link_to 'Desativar', enable_product_model_path(p.id), method: :patch %></td>
          <% else %>
            <td><%= link_to 'Ativar', enable_product_model_path(p.id), method: :patch %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/product_models/new.html.erb
<h3>Novo Produto</h3>
<div style="width: 46rem;">
  <% unless @errors == []%>
    <div class="alert alert-warning">
      <ul>
        <% @errors.each do |msg| %>
          <li><%=msg%></li>
        <%end%>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: ProductModel.new) do |f|%>
    <div class="form-group">
      <%= f.label :name, 'Nome'%>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :weight, 'Peso'%>
      <%= f.text_field :weight, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :height, 'Altura'%>
      <%= f.text_field :height, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :width, 'Largura'%>
      <%= f.text_field :width, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :length, 'Profundidade'%>
      <%= f.text_field :length, class: 'form-control'%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :category_id, 'Categoria'%><br>
      <%= f.collection_select(:category_id, Category.all, :id, :name)%>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :provider_id, 'Fornecedor'%><br>
      <%= f.collection_select(:provider_id, Provider.all, :id, :trading_name) %>
    </div>
    <br>
    <%= f.submit 'Gravar', class: 'btn btn-success'%>
  <%end%>
</div>

app/views/product_models/show.html.erb
<h3><%= @product_model.name %></h3>
<ul class="list-group" style="width: 25rem;">
  <li class="list-group-item"><strong>Peso: </strong><%= @product_model.weight %> gramas</li>
  <li class="list-group-item"><strong>Dimensões: </strong><%= @product_model.dimensions %></li>
  <li class="list-group-item"><strong>SKU: </strong><%= @product_model.sku %></li>
  <li class="list-group-item"><strong>Categoria: </strong><%= @product_model.category.name %></li>
  <li class="list-group-item"><strong>Fornecedor: </strong><%= @product_model.provider.trading_name %> </li>
  <li class="list-group-item"><strong>Status: </strong><%= @product_model.enum_name(:status, @product_model.status)%></li>
</ul>

<% if user_signed_in? %>
  <br>
  <% if @product_model.enabled? %>
    <%= link_to 'Desativar', enable_product_model_path(@product_model.id), method: :patch, class: 'btn btn-danger'%>
  <% else %>
    <%= link_to 'Ativar', enable_product_model_path(@product_model.id), method: :patch, class: 'btn btn-success' %>
  <% end %>
<% end %>

<br><br><br>
<h3> Galpões com estoque disponível </h3>
<% if @items.empty? %>
  <p>Produto fora de estoque</p>
<% else %>
  <table class="table" style="width: 25rem;">
    <thead>
      <tr>
        <th>Galpão</th>
        <th>Quantidade</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each_pair do |warehouse, qtd| %>
        <tr id = <%= warehouse.id %>>
          <td><%= link_to warehouse.name, warehouse %></td>
          <td><%= qtd %></td>
        </tr>
      <% end %> 
    </tbody>
  </table>
<% end %>


<br><br><br>
<% if user_signed_in? %>
  <h3>Entrada de itens</h3>

  <div class="form-group" style="width: 25rem;">
    <% if @error %>
      <ul>
        <li><%= @error %></li>
      </ul>
    <% end %>

    <%= form_with(url: product_entry_product_model_path(@product_model.id)) do |f| %>
      <div>
        <%= f.label :quantity, 'Quantidade'%>
        <%= f.number_field :quantity, class: 'form-control'%>
      </div>
      <br>
      <div>
        <%= f.label :warehouse_id, 'Galpão destino'%>
        <br>
        <%= f.collection_select(:warehouse_id, @warehouses, :id, :name)%>
      </div>
      <br>
      <%= f.submit 'Confirmar', class: 'btn btn-success'%>
    <% end %>
  </div>

<% end %>