config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :warehouses, only:[:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'add_category', on: :member
    post 'register_category', on: :member
    get 'search', on: :collection
    get 'confirm', on: :member
    patch 'activate', on: :member
    get 'disabled', on: :collection
  end
  resources :providers, only:[:index, :show, :new, :create] 
  resources :product_models, only:[:index, :show, :new, :create, :edit, :update] do
    patch 'enable', on: :member
    post 'product_entry', on: :member
  end
  resources :product_bundles, only:[:index, :new, :create, :show]
  resources :categories, only:[:index, :show, :new, :create]
  resources :product_items, only:[:new]
  get '/product_items/entry', to: 'product_items#entry'
  post '/product_items/entry', to: 'product_items#process_entry'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do #versionamento de api
      resources :warehouses, only:[:index, :show, :create]
      resources :product_models, only:[:index, :show, :create]
      resources :suppliers, only:[:index, :show, :create]
    end
    
  end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.enabled
    @disabled_warehouses = Warehouse.disabled
  end
end

app/views/home/index.html.erb
<h3>Boas vindas ao sistema de gestão de estoques</h3>
<br>

<% unless @warehouses.nil? %>
  <h3>Galpões cadastrados</h3>
  <div style="display: flex;">
    <%@warehouses.each do |w|%>
      <div class="card" style="width: 18rem; margin-right: 15px;" id="card-<%=w.id%>">
        <div class="card-body">
          <h5 class="card-title"><%= w.name %></h5>
          <p class="card-text"><%= w.description %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Código: <%= w.code %></li>
          <li class="list-group-item">Endereço: <%= w.address %>, <%= w.number %></li>
          <li class="list-group-item">CEP: <%= w.postal_code %></li>
        </ul>
        <iframe src="https://www.google.com.br/maps?q=<%= w.postal_code %>,%20Brasil&output=embed"
                style="margin: 5%; border-radius: 5px;" allowfullscreen="" loading="lazy"></iframe>
        <div class="card-body">
          <%= link_to 'Detalhes', w, class: 'card-link'%>
        </div>
      </div>
      <br>
    <%end%>
  </div>
<% else %>
  <h3> Nenhum galpão cadastrado</h3>
<% end %>
<br>
<% if user_signed_in? && @disabled_warehouses.empty? == false %>
  <%= link_to 'Galpões desativados', disabled_warehouses_path %>
<% end %>