config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :warehouses, only:[:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'add_category', on: :member
    post 'register_category', on: :member
    get 'search', on: :collection
    get 'confirm', on: :member
    patch 'activate', on: :member
    get 'disabled', on: :collection
  end
  resources :providers, only:[:index, :show, :new, :create] 
  resources :product_models, only:[:index, :show, :new, :create, :edit, :update] do
    patch 'enable', on: :member
    post 'product_entry', on: :member
  end
  resources :product_bundles, only:[:index, :new, :create, :show]
  resources :categories, only:[:index, :show, :new, :create]
  resources :product_items, only:[:new]
  get '/product_items/entry', to: 'product_items#entry'
  post '/product_items/entry', to: 'product_items#process_entry'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do #versionamento de api
      resources :warehouses, only:[:index, :show, :create]
      resources :product_models, only:[:index, :show, :create]
      resources :suppliers, only:[:index, :show, :create]
    end
    
  end
  

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :product_models
    has_many :warehouse_categories
    has_many :warehouses, through: :warehouse_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @errors = []
  end

  def create
    c_params = params.require(:category).permit(:name)
    @category = Category.new(c_params)

    if @category.save
    redirect_to categories_path, notice: 'Categoria cadastrada com sucesso'
    else
      @errors = @category.errors.full_messages
      flash.now[:alert] = 'Não foi possível cadastrar a categoria'
      render 'new'
    end

  end

  def show
    @category = Category.find(params[:id])
    @warehouses = @category.warehouses
  end
  
end

app/views/categories/index.html.erb
<h3> Categorias</h3>

<% if @categories.empty? %>
  <p>Nenhuma categoria cadastrada</p>
  
<% else %>
  <p>Categorias cadastradas: <%= @categories.count %></p>
  <br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Galpões cadastrados</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr id="cat-<%= category.id %>">
          <td><%= category.name %></td>
          <td><%= category.warehouses.count %></td>
          <td><%= link_to 'Detalhes', category%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/categories/new.html.erb
<h3>Nova categoria</h3>
<br>
<div style="width: 46rem;">
  <% unless @errors == []%>
    <div class="alert alert-warning">
      <ul>
        <% @errors.each do |msg| %>
          <li><%=msg%></li>
        <%end%>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @category) do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Nome'%>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <br>
    <%=f.submit 'Gravar', class: 'btn btn-success'%>
  <% end %>
</div>

app/views/categories/show.html.erb
<h3>Produtos na categoria <%= @category.name %></h3>

<% if @category.product_models.empty? %>
  <p>Nenhum produto cadastrado nessa categoria</p>
<% else %>
  <ul class="list-group" style="width: 25rem;">
    <% @category.product_models.each do |product| %>
      <li class="list-group-item"><%= link_to product.name, product_model_path(product.id) %></li>
    <% end %>
  </ul>
<% end %>
<br><br>

<% if @warehouses.empty? %>
  <p>Nenhum galpão cadastrado nessa categoria</p>
<% else %>
  <table class="table" style="width: 25rem;">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Código</th>
        <th>Cep</th>
      </tr>
    </thead>
    <tbody>
      <% @warehouses.each do |warehouse| %>
        <tr>
          <td><%= warehouse.name %></td>
          <td><%= warehouse.code %></td>
          <td><%= warehouse.postal_code %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>