config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :warehouses, only:[:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'add_category', on: :member
    post 'register_category', on: :member
    get 'search', on: :collection
    get 'confirm', on: :member
    patch 'activate', on: :member
    get 'disabled', on: :collection
  end
  resources :providers, only:[:index, :show, :new, :create] 
  resources :product_models, only:[:index, :show, :new, :create, :edit, :update] do
    patch 'enable', on: :member
    post 'product_entry', on: :member
  end
  resources :product_bundles, only:[:index, :new, :create, :show]
  resources :categories, only:[:index, :show, :new, :create]
  resources :product_items, only:[:new]
  get '/product_items/entry', to: 'product_items#entry'
  post '/product_items/entry', to: 'product_items#process_entry'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do #versionamento de api
      resources :warehouses, only:[:index, :show, :create]
      resources :product_models, only:[:index, :show, :create]
      resources :suppliers, only:[:index, :show, :create]
    end
    
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav" style="margin-left: 15px;">
          <%= link_to 'Warehouse App', root_path, class: 'navbar-brand' %>
          <%= link_to 'Início', root_path, class: 'nav-link' %>
          <%= link_to 'Fornecedores', providers_path, class: 'nav-link'%>
          <%= link_to 'Produtos', product_models_path, class: 'nav-link'%>
          <%= link_to 'Kits', product_bundles_path, class: 'nav-link'%>
          <%= link_to 'Categorias', categories_path, class: 'nav-link'%>
        </div>
        <div class="container-fluid">
          <%= form_with(url: search_warehouses_path, method: :get, class: 'd-flex') do |f|%>
              <%= f.label :query, 'Buscar galpão'%>
              <%= f.text_field :query, class: 'form-control me-2'%>
              <%= f.submit 'Pesquisar', class: 'btn btn-success'%>
          <% end %>
        </div>
        <div class="navbar-nav">
          <% unless user_signed_in? %>
            <%= link_to 'Entrar', new_user_session_path, class: 'nav-link'%>
          <% end %>
        </div>
      </nav>

      <% if user_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-nav" style="margin-left: 15px;">
          <%= link_to 'Novo galpão', new_warehouse_path, class: 'nav-link'%>
          <%= link_to 'Novo produto', new_product_model_path, class: 'nav-link'%>
          <%= link_to 'Novo kit', new_product_bundle_path, class: 'nav-link'%>
          <%= link_to 'Novo fornecedor', new_provider_path, class: 'nav-link'%>
          <%= link_to 'Nova Categoria', new_category_path, class: 'nav-link'%>
          <%= link_to 'Entrada de itens', product_items_entry_path, class: 'nav-link'%>
        </div>
        </nav>
        <div>
          <p style="text-align: right; margin: 15px;">
            Olá <%= current_user.email %> - 
            <%= link_to 'Sair', destroy_user_session_path, :method => :delete, class: 'link-danger'%>
          </p>
        </div>
      <% end %>
    </header>
    <% flash.each do |type, msg| %>
      <% if type == 'alert' %>
        <div style="margin: 15px;" class="alert alert-danger" role="alert">
          <%= msg %>
        </div>
      <% elsif type == 'notice' %>
        <div style="margin: 15px;" class="alert alert-success" role="alert">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <main style="margin: 15px;">
      <%= yield %>
    </main>
  </body>
</html>